config/routes.rb
Rails.application.routes.draw do
  resources :responses
  resources :messages
  resources :type_cards
  resources :cards
  resources :type_users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "index#index"
end

app/models/type_user.rb
class TypeUser < ApplicationRecord
end

app/controllers/type_users_controller.rb
class TypeUsersController < ApplicationController
  before_action :set_type_user, only: [:show, :edit, :update, :destroy]

  # GET /type_users
  # GET /type_users.json
  def index
    @type_users = TypeUser.all
  end

  # GET /type_users/1
  # GET /type_users/1.json
  def show
  end

  # GET /type_users/new
  def new
    @type_user = TypeUser.new
  end

  # GET /type_users/1/edit
  def edit
  end

  # POST /type_users
  # POST /type_users.json
  def create
    @type_user = TypeUser.new(type_user_params)

    respond_to do |format|
      if @type_user.save
        format.html { redirect_to @type_user, notice: 'Type user was successfully created.' }
        format.json { render :show, status: :created, location: @type_user }
      else
        format.html { render :new }
        format.json { render json: @type_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /type_users/1
  # PATCH/PUT /type_users/1.json
  def update
    respond_to do |format|
      if @type_user.update(type_user_params)
        format.html { redirect_to @type_user, notice: 'Type user was successfully updated.' }
        format.json { render :show, status: :ok, location: @type_user }
      else
        format.html { render :edit }
        format.json { render json: @type_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /type_users/1
  # DELETE /type_users/1.json
  def destroy
    @type_user.destroy
    respond_to do |format|
      format.html { redirect_to type_users_url, notice: 'Type user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type_user
      @type_user = TypeUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_user_params
      params.require(:type_user).permit(:type_usr, :data)
    end
end

app/helpers/type_users_helper.rb
module TypeUsersHelper
end

app/views/type_users/_form.html.erb
<%= form_with(model: type_user, local: true) do |form| %>
  <% if type_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type_user.errors.count, "error") %> prohibited this type_user from being saved:</h2>

      <ul>
      <% type_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type_usr %>
    <%= form.number_field :type_usr %>
  </div>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_field :data %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/type_users/edit.html.erb
<h1>Editing Type User</h1>

<%= render 'form', type_user: @type_user %>

<%= link_to 'Show', @type_user %> |
<%= link_to 'Back', type_users_path %>

app/views/type_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Type Users</h1>

<table>
  <thead>
    <tr>
      <th>Type usr</th>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @type_users.each do |type_user| %>
      <tr>
        <td><%= type_user.type_usr %></td>
        <td><%= type_user.data %></td>
        <td><%= link_to 'Show', type_user %></td>
        <td><%= link_to 'Edit', edit_type_user_path(type_user) %></td>
        <td><%= link_to 'Destroy', type_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type User', new_type_user_path %>

app/views/type_users/new.html.erb
<h1>New Type User</h1>

<%= render 'form', type_user: @type_user %>

<%= link_to 'Back', type_users_path %>

app/views/type_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type usr:</strong>
  <%= @type_user.type_usr %>
</p>

<p>
  <strong>Data:</strong>
  <%= @type_user.data %>
</p>

<%= link_to 'Edit', edit_type_user_path(@type_user) %> |
<%= link_to 'Back', type_users_path %>