config/routes.rb
Rails.application.routes.draw do
  resources :responses
  resources :messages
  resources :type_cards
  resources :cards
  resources :type_users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "index#index"
end

app/models/card.rb
class Card < ApplicationRecord
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:title, :type_usr_id, :type_card_id, :description, :image_url, :movie_url, :link_url, :headline, :context)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :type_usr_id %>
    <%= form.number_field :type_usr_id %>
  </div>

  <div class="field">
    <%= form.label :type_card_id %>
    <%= form.text_field :type_card_id %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>

  <div class="field">
    <%= form.label :movie_url %>
    <%= form.text_field :movie_url %>
  </div>

  <div class="field">
    <%= form.label :link_url %>
    <%= form.text_field :link_url %>
  </div>

  <div class="field">
    <%= form.label :headline %>
    <%= form.text_field :headline %>
  </div>

  <div class="field">
    <%= form.label :context %>
    <%= form.text_field :context %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Type usr</th>
      <th>Type card</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Movie url</th>
      <th>Link url</th>
      <th>Headline</th>
      <th>Context</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.title %></td>
        <td><%= card.type_usr_id %></td>
        <td><%= card.type_card_id %></td>
        <td><%= card.description %></td>
        <td><%= card.image_url %></td>
        <td><%= card.movie_url %></td>
        <td><%= card.link_url %></td>
        <td><%= card.headline %></td>
        <td><%= card.context %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @card.title %>
</p>

<p>
  <strong>Type usr:</strong>
  <%= @card.type_usr_id %>
</p>

<p>
  <strong>Type card:</strong>
  <%= @card.type_card_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @card.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @card.image_url %>
</p>

<p>
  <strong>Movie url:</strong>
  <%= @card.movie_url %>
</p>

<p>
  <strong>Link url:</strong>
  <%= @card.link_url %>
</p>

<p>
  <strong>Headline:</strong>
  <%= @card.headline %>
</p>

<p>
  <strong>Context:</strong>
  <%= @card.context %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>