config/routes.rb
Rails.application.routes.draw do
  resources :responses
  resources :messages
  resources :type_cards
  resources :cards
  resources :type_users
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "index#index"
end

app/models/type_card.rb
class TypeCard < ApplicationRecord
end

app/controllers/type_cards_controller.rb
class TypeCardsController < ApplicationController
  before_action :set_type_card, only: [:show, :edit, :update, :destroy]

  # GET /type_cards
  # GET /type_cards.json
  def index
    @type_cards = TypeCard.all
  end

  # GET /type_cards/1
  # GET /type_cards/1.json
  def show
  end

  # GET /type_cards/new
  def new
    @type_card = TypeCard.new
  end

  # GET /type_cards/1/edit
  def edit
  end

  # POST /type_cards
  # POST /type_cards.json
  def create
    @type_card = TypeCard.new(type_card_params)

    respond_to do |format|
      if @type_card.save
        format.html { redirect_to @type_card, notice: 'Type card was successfully created.' }
        format.json { render :show, status: :created, location: @type_card }
      else
        format.html { render :new }
        format.json { render json: @type_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /type_cards/1
  # PATCH/PUT /type_cards/1.json
  def update
    respond_to do |format|
      if @type_card.update(type_card_params)
        format.html { redirect_to @type_card, notice: 'Type card was successfully updated.' }
        format.json { render :show, status: :ok, location: @type_card }
      else
        format.html { render :edit }
        format.json { render json: @type_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /type_cards/1
  # DELETE /type_cards/1.json
  def destroy
    @type_card.destroy
    respond_to do |format|
      format.html { redirect_to type_cards_url, notice: 'Type card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type_card
      @type_card = TypeCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_card_params
      params.require(:type_card).permit(:name)
    end
end

app/helpers/type_cards_helper.rb
module TypeCardsHelper
end

app/views/type_cards/_form.html.erb
<%= form_with(model: type_card, local: true) do |form| %>
  <% if type_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type_card.errors.count, "error") %> prohibited this type_card from being saved:</h2>

      <ul>
      <% type_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/type_cards/edit.html.erb
<h1>Editing Type Card</h1>

<%= render 'form', type_card: @type_card %>

<%= link_to 'Show', @type_card %> |
<%= link_to 'Back', type_cards_path %>

app/views/type_cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Type Cards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @type_cards.each do |type_card| %>
      <tr>
        <td><%= type_card.name %></td>
        <td><%= link_to 'Show', type_card %></td>
        <td><%= link_to 'Edit', edit_type_card_path(type_card) %></td>
        <td><%= link_to 'Destroy', type_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Type Card', new_type_card_path %>

app/views/type_cards/new.html.erb
<h1>New Type Card</h1>

<%= render 'form', type_card: @type_card %>

<%= link_to 'Back', type_cards_path %>

app/views/type_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @type_card.name %>
</p>

<%= link_to 'Edit', edit_type_card_path(@type_card) %> |
<%= link_to 'Back', type_cards_path %>